### ISSUE TITLE
Re-enable "New VMs" approach in HyperV

### ISSUE THREAD

**Issue by iamshital** [LIS/LISAv2#108]
PR#102 : The current implementation strictly uses checkpoint method for HyperV mode. However, we're missing a key functionality here - First Boot. In Azure, we have an option called as - EconomyMode. Which decides, whether to run test on Same VMs again and again, or to create new VMs for each test. Nowadays, EconomyMode is not being used because, many times, we've found the boot related issues in First Boot. In conjunction with "Checkpoint" method, I strongly recommend to re-enable "New VMs" approach for HyperV tests as well. And let the user decide, how it wants to run the tests.

**Comment by juhlee-microsoft** [comment]
I think this was designed for options. It would be New VM mode in Azure testing, as Snapshot mode in Hyper-V.

**Comment by juhlee-microsoft** [comment]
Snapshot or its provisioning is helpful for quick VM deployment, but we are testing against the changes and moving target. Also this idea comes out from two domains which have different operation pattern. According to Azure, VM booting can be a still issue by Azure host. Our test scope is Linux GOS VM on top of Azure host.(this host is NOT our scope or work) If this is the case, then we should spend more time for VM boot rather than other planned tests. I still think new design should take two different VM provisioning way per hypervisor platform type. Also put 'VM boot' exercise before other tests in schedule. Getting stabilize VM boot may help the rest of tests.

**Comment by ader1990** [comment]
@iamshital please close this issue, if it has been addressed already (I see it has been addressed)
