### ISSUE TITLE
Test case BVT-VERIFY-BOOT-ERROR-WARNINGS fails on Azure Ubuntu 18.04

### ISSUE THREAD

**Issue by ader1990** [LIS/LISAv2#516]
On Azure Ubuntu 18.04, we can see the following kernel errors caught by the BVT-VERIFY-BOOT-ERROR-WARNINGS test case:
1.	snapd[1184]: 2018/12/10 08:26:19.814637 helpers.go:119: error trying to compare the snap system key: system-key missing on disk
2.	HV_FCOPY: open /dev/vmbus/hv_fcopy failed; error: 2 No such file or directory
3.	systemd-resolved[867]: Server returned error NXDOMAIN, mitigating potential DNS violation DVE-2018-0001, retrying transaction with reduced feature level UDP.

If they are false positives, we should add them to:
https://github.com/LIS/LISAv2/blob/master/XML/Other/ignorable-boot-errors.xml

@simonxiaoss @juhlee-microsoft @LiliDeng @lizzha can you confirm that these errors are all false positives?

**Comment by LiliDeng** [comment]
Ubuntu 18.04 
12/17/2018 03:45:43 AM : INFO : Errors: 763:Dec 17 03:29:12 LISAv2-SingleVM-lili-HC16-20181216192617-role-0 HV_FCOPY: open /dev/vmbus/hv_fcopy failed; error: 2 No such file or directory826:Dec 17 03:29:12 LISAv2-SingleVM-lili-HC16-20181216192617-role-0 snapd[1192]: 2018/12/17 03:29:12.216971 helpers.go:119: error trying to compare the snap system key: system-key missing on disk911:Dec 17 03:29:20 LISAv2-SingleVM-lili-HC16-20181216192617-role-0 systemd-resolved[878]: Server returned error NXDOMAIN, mitigating potential DNS violation DVE-2018-0001, retrying transaction with reduced feature level UDP.912:Dec 17 03:29:20 LISAv2-SingleVM-lili-HC16-20181216192617-role-0 systemd-resolved[878]: message repeated 3 times: [ Server returned error NXDOMAIN, mitigating potential DNS violation DVE-2018-0001, retrying transaction with reduced feature level UDP.]
12/17/2018 03:45:43 AM : INFO : warnings: 759:Dec 17 03:29:12 LISAv2-SingleVM-lili-HC16-20181216192617-role-0 python3[1181]: 2018/12/17 03:29:11.836003 WARNING Server preferred version:2015-04-05845:Dec 17 03:29:13 LISAv2-SingleVM-lili-HC16-20181216192617-role-0 python3[1181]: 2018/12/17 03:29:13.501639 WARNING Hostname record does not exist, creating [/var/lib/waagent/published_hostname] with hostname [LISAv2-SingleVM-lili-HC16-20181216192617-role-0]869:Dec 17 03:29:14 LISAv2-SingleVM-lili-HC16-20181216192617-role-0 python3[1181]: 2018/12/17 03:29:14.183060 WARNING Dhcp client is not running.915:Dec 17 03:29:20 LISAv2-SingleVM-lili-HC16-20181216192617-role-0 systemd[1]: Starting Write warning to Azure ephemeral disk...916:Dec 17 03:29:20 LISAv2-SingleVM-lili-HC16-20181216192617-role-0 root: Added ephemeral disk warning to /mnt/DATALOSS_WARNING_README.txt917:Dec 17 03:29:20 LISAv2-SingleVM-lili-HC16-20181216192617-role-0 systemd[1]: Started Write warning to Azure ephemeral disk.

**Comment by LiliDeng** [comment]
@ader1990 This is for LIS? HV_FCOPY: open /dev/vmbus/hv_fcopy failed; error: 2 No such file or directory, should we let Dev take a look?

**Comment by chvalean** [comment]
> @ader1990 This is for LIS? HV_FCOPY: open /dev/vmbus/hv_fcopy failed; error: 2 No such file or directory, should we let Dev take a look?

this should be expected in Azure, as fcopy is not available there.

**Comment by asofron** [comment]
Added the 3 errors ,seems to failed due to following warning now : 

01/03/2019 09:54:09 AM : INFO : warnings: 752:Jan  3 09:53:22 LISAv2-OneVM-staginglisav2-VQ52-20190103095049-role-0 python3[1172]: 2019/01/03 09:53:21.678010 WARNING Server preferred version:2015-04-05843:Jan  3 09:53:23 LISAv2-OneVM-staginglisav2-VQ52-20190103095049-role-0 python3[1172]: 2019/01/03 09:53:23.289829 WARNING Hostname record does not exist, creating [/var/lib/waagent/published_hostname] with hostname [LISAv2-OneVM-staginglisav2-VQ52-20190103095049-role-0]866:Jan  3 09:53:24 LISAv2-OneVM-staginglisav2-VQ52-20190103095049-role-0 python3[1172]: 2019/01/03 09:53:24.104505 WARNING Dhcp client is not running.913:Jan  3 09:53:34 LISAv2-OneVM-staginglisav2-VQ52-20190103095049-role-0 systemd[1]: Starting Write warning to Azure ephemeral disk...914:Jan  3 09:53:34 LISAv2-OneVM-staginglisav2-VQ52-20190103095049-role-0 root: Added ephemeral disk warning to /mnt/DATALOSS_WARNING_README.txt915:Jan  3 09:53:34 LISAv2-OneVM-staginglisav2-VQ52-20190103095049-role-0 systemd[1]: Started Write warning to Azure ephemeral disk.

Fixing this one as well

**Comment by chvalean** [comment]
Resolved in #569
