### ISSUE TITLE
Need Azure Memory test cases

### ISSUE THREAD

**Issue by juhlee-microsoft** [LIS/LISAv2#749]
There are 31 memory tests for Hyper-V, but none for Azure.

Need to create Azure memory test cases.

1. Verify existing memory size based on the designed one. Capture memory info from VM size information.
2. Verify memory size consistency in rebooting
3.  Use benchmark tool or open source tools.

**Comment by lizzha** [comment]
The existing memory cases for HyperV doesn't apply to Azure. This issue is for adding new cases.
Suggest to create one issue for each case, so that the workload of one issue won't be too much.

There's a case named BVT-HOT-VM-RESIZE which can be imported from azure-linux-automation. It deploys the VM, verifies core number/memory size, then resize the VM, verifies new core number /memory size. It covers the first requirement.
I think we can start from importing the case BVT-HOT-VM-RESIZE.

**Comment by juhlee-microsoft** [comment]
OK, I will close this issue as soon as I create new internal task items.

**Comment by lizzha** [comment]
I‘ve created an internal task for adding case VM-HOT-RESIZE

**Comment by lizzha** [comment]
https://github.com/LIS/LISAv2/pull/768
