### ISSUE TITLE
Add VMsize filtering in RDMA IB test case

### ISSUE THREAD

**Issue by juhlee-microsoft** [LIS/LISAv2#798]
New filter will display warning when unsupported VM Size is selected in RDMA IB tests.

**Comment by juhlee-microsoft** [comment]
Recently discussed with @LiliDeng 
If new proposal comes, we will review for this issue also.

**Comment by chvalean** [comment]
Tests should not be tied to a certain element like feature.
Tests should have checks for basic feature presence to allow them to run, but otherwise I would say to not hardcode this.
New VMs might appear, so the tests should be capable to run on those without this being restricted.
Also, one should know the feature requirements, and not the test drive that.

**Comment by juhlee-microsoft** [comment]
@LiliDeng Please check out if VM Size has letter 'r' or 'mr'. 'r' means it supports RDMA.

**Comment by juhlee-microsoft** [comment]
Close because we only hold P0
